import { RoomSettings } from "./types";

// ===== WORD LISTS =====

const commonWords: string[] = [
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "i",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "great",
  "between",
  "need",
  "large",
  "under",
  "never",
  "each",
  "right",
  "early",
  "began",
  "always",
  "those",
  "both",
  "often",
  "where",
  "every",
  "keep",
  "head",
  "still",
  "while",
  "turn",
  "real",
  "leave",
  "might",
  "long",
  "since",
  "must",
  "high",
  "such",
  "follow",
  "act",
  "why",
  "ask",
  "men",
  "change",
  "went",
  "light",
  "kind",
  "off",
  "place",
  "same",
  "point",
  "help",
  "much",
  "big",
  "here",
  "old",
  "life",
  "tell",
  "write",
  "end",
  "run",
  "move",
  "try",
  "home",
  "show",
  "hand",
  "part",
  "next",
  "near",
  "live",
  "start",
  "story",
  "eye",
  "small",
  "open",
  "play",
  "call",
  "read",
  "last",
  "line",
  "three",
  "name",
  "state",
];

const mediumWords: string[] = [
  "ability",
  "absence",
  "academy",
  "account",
  "achieve",
  "acquire",
  "address",
  "advance",
  "against",
  "airline",
  "already",
  "amazing",
  "ancient",
  "another",
  "anxiety",
  "applied",
  "attempt",
  "average",
  "balance",
  "battery",
  "believe",
  "benefit",
  "billion",
  "brother",
  "brought",
  "building",
  "cabinet",
  "captain",
  "capture",
  "careful",
  "carrier",
  "central",
  "century",
  "certain",
  "chapter",
  "chicken",
  "citizen",
  "climate",
  "clothes",
  "collect",
  "college",
  "combine",
  "comfort",
  "command",
  "comment",
  "company",
  "compare",
  "complex",
  "concept",
  "concern",
  "confirm",
  "connect",
  "contact",
  "content",
  "context",
  "control",
  "convert",
  "correct",
  "council",
  "counter",
  "country",
  "crucial",
  "culture",
  "current",
  "customer",
  "database",
  "dealing",
  "decades",
  "decided",
  "defense",
  "deliver",
  "despite",
  "develop",
  "digital",
  "display",
  "diverse",
  "dynamic",
  "eastern",
  "economy",
  "edition",
  "element",
  "emotion",
  "enabled",
  "endless",
  "enforce",
  "enhance",
  "example",
  "excited",
  "execute",
  "expense",
  "explain",
  "explore",
  "express",
  "extends",
  "extreme",
  "factors",
  "faculty",
  "feature",
  "finally",
  "finance",
  "foreign",
  "formula",
  "fortune",
  "forward",
  "founder",
  "freedom",
  "genuine",
  "glimpse",
  "grateful",
  "gravity",
  "growing",
  "guidance",
  "habitat",
  "handling",
  "harmony",
  "healthy",
  "helpful",
  "highway",
  "history",
  "however",
  "imagine",
  "improve",
  "include",
  "initial",
  "insight",
  "inspect",
  "instead",
  "justice",
  "kitchen",
  "knowing",
  "landing",
  "largely",
  "leather",
  "library",
  "limited",
  "logical",
  "machine",
  "manager",
  "married",
  "massive",
  "measure",
  "medical",
  "meeting",
  "mention",
  "message",
  "million",
  "mineral",
  "missing",
  "mixture",
  "monitor",
  "morning",
  "musical",
  "mystery",
  "natural",
  "neither",
  "network",
  "notable",
  "nothing",
  "nuclear",
  "nursing",
  "obvious",
  "offense",
  "officer",
  "opinion",
  "organic",
  "outline",
  "outside",
  "overall",
  "package",
  "parking",
  "partial",
  "partner",
  "passage",
  "patient",
  "pattern",
  "payment",
  "penalty",
  "pension",
  "percent",
  "perfect",
  "perform",
  "perhaps",
];

const hardWords: string[] = [
  "achievement",
  "acknowledge",
  "acquisition",
  "administration",
  "advertisement",
  "approximately",
  "architecture",
  "authentication",
  "bibliography",
  "breakthrough",
  "bureaucracy",
  "characteristic",
  "circumstances",
  "collaboration",
  "communication",
  "comprehensive",
  "concentration",
  "configuration",
  "consciousness",
  "consequently",
  "constellation",
  "constitutional",
  "controversial",
  "correspondence",
  "demonstration",
  "determination",
  "differentiate",
  "disappointing",
  "discrimination",
  "distinguished",
  "documentation",
  "effectiveness",
  "electromagnetic",
  "entertainment",
  "environmental",
  "establishment",
  "extraordinary",
  "fundamentally",
  "implementation",
  "independently",
  "infrastructure",
  "initialization",
  "institutional",
  "interpretation",
  "investigation",
  "knowledgeable",
  "manufacturing",
  "miscellaneous",
  "nevertheless",
  "opportunities",
  "organizational",
  "parliamentary",
  "pharmaceutical",
  "philosophical",
  "predominantly",
  "professionally",
  "psychological",
  "questionnaire",
  "recommendation",
  "representative",
  "responsibility",
  "simultaneously",
  "sophisticated",
  "substantially",
  "technological",
  "transformation",
  "understanding",
  "unfortunately",
  "vulnerability",
  "unprecedented",
  "acknowledgement",
  "disproportionate",
  "entrepreneurship",
  "incomprehensible",
  "indistinguishable",
  "internationalization",
  "multidimensional",
  "oversimplification",
  "straightforward",
  "uncharacteristically",
  "counterproductive",
  "miscommunication",
  "interdisciplinary",
  "compartmentalize",
  "disestablishment",
  "procrastination",
  "telecommunications",
  "microprocessor",
  "metamorphosis",
  "psychophysiology",
];

// ===== SENTENCES & QUOTES =====

const sentences: string[] = [
  "The quick brown fox jumps over the lazy dog near the riverbank.",
  "Programming is the art of telling another human what one wants the computer to do.",
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
  "The best way to predict the future is to invent it.",
  "Simplicity is the ultimate sophistication in software design.",
  "Code is like humor. When you have to explain it, it is bad.",
  "First, solve the problem. Then, write the code.",
  "Experience is the name everyone gives to their mistakes.",
  "The only way to learn a new programming language is by writing programs in it.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "Talk is cheap. Show me the code.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The most dangerous phrase in the language is we have always done it this way.",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
  "The best error message is the one that never shows up.",
  "A language that does not affect the way you think about programming is not worth knowing.",
  "The computer was born to solve problems that did not exist before.",
  "Sometimes it pays to stay in bed on Monday rather than spending the rest of the week debugging Monday code.",
  "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are by definition not smart enough to debug it.",
  "It is not enough for code to work. Clean code is simple and direct.",
  "The function of good software is to make the complex appear to be simple.",
  "Perfection is achieved not when there is nothing more to add but when there is nothing left to take away.",
  "Before software can be reusable it first has to be usable.",
  "Make it work, make it right, make it fast.",
  "Walking on water and developing software from a specification are easy if both are frozen.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "The most disastrous thing that you can ever learn is your first programming language.",
  "Software is like entropy: it is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics; it always increases.",
  "Truth can only be found in one place: the code.",
  "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime.",
];

const paragraphs: string[] = [
  "The art of programming is the skill of controlling complexity. It is the organization of thoughts into a form that a machine can follow while remaining comprehensible to fellow developers who will maintain the code long after its author has moved on.",
  "In the world of software development, there are no silver bullets. Each project brings its own unique challenges that require creative solutions. The best engineers are those who can adapt their approach to fit the problem at hand rather than forcing every problem into a familiar pattern.",
  "Version control is not just about saving copies of your files. It is a time machine that lets you explore the evolution of your codebase, understand why decisions were made, and collaborate with others without stepping on each other's work. Learning to use it effectively is one of the most important skills a developer can have.",
  "Testing is not about finding bugs. It is about building confidence that your code works as intended. A well-tested codebase gives you the freedom to refactor, optimize, and extend without fear of breaking existing functionality.",
  "The terminal is your command center. Learning to navigate the filesystem, manipulate text, and automate repetitive tasks from the command line will make you significantly more productive than relying solely on graphical interfaces.",
  "When you encounter a bug, resist the urge to immediately start changing code. Instead, take a step back and form a hypothesis about what might be wrong. Then design an experiment to test that hypothesis. This scientific approach to debugging will save you countless hours of random code changes.",
  "Good documentation is not a luxury. It is a necessity. Your future self is your most important user, and that person will have forgotten why you made the decisions you made today. Write down your reasoning while it is fresh in your mind.",
  "The best code is the code you never have to write. Before implementing a feature, ask yourself whether it is truly necessary. Every line of code is a liability that must be maintained, tested, and understood by others.",
  "Pair programming is not about two people doing the work of one. It is about two minds approaching a problem from different angles simultaneously. The navigator sees the forest while the driver focuses on the trees.",
  "Technical debt is not inherently bad. Sometimes taking on debt is the right business decision to meet a deadline or validate an idea quickly. The problem is unmanaged debt that accumulates interest until the codebase becomes unmaintainable.",
];

const quotes: string[] = [
  "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "In the middle of difficulty lies opportunity.",
  "Life is what happens when you are busy making other plans.",
  "The greatest glory in living lies not in never falling but in rising every time we fall.",
  "It is during our darkest moments that we must focus to see the light.",
  "The purpose of our lives is to be happy.",
  "You will face many defeats in life but never let yourself be defeated.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "It is better to fail in originality than to succeed in imitation.",
  "Success is not final. Failure is not fatal. It is the courage to continue that counts.",
  "Do not judge each day by the harvest you reap but by the seeds that you plant.",
  "The only impossible journey is the one you never begin.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "In three words I can sum up everything I have learned about life: it goes on.",
  "The way to get started is to quit talking and begin doing.",
  "If life were predictable it would cease to be life and be without flavor.",
  "Life is a succession of lessons which must be lived to be understood.",
  "You only live once but if you do it right once is enough.",
];

// ===== CODE SNIPPETS =====

const codeSnippets: Record<string, string[]> = {
  javascript: [
    "const handleClick = (event) => { event.preventDefault(); setState(prev => !prev); };",
    "function fetchData(url) { return fetch(url).then(res => res.json()).catch(err => console.error(err)); }",
    "const debounce = (fn, delay) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); }; };",
    'export default function App() { const [data, setData] = useState([]); return <div className="app">{data.map(item => <Card key={item.id} {...item} />)}</div>; }',
    'const router = express.Router(); router.get("/api/users", async (req, res) => { const users = await User.find(); res.json(users); });',
    "class EventEmitter { constructor() { this.events = {}; } on(event, cb) { (this.events[event] ||= []).push(cb); } emit(event, ...args) { this.events[event]?.forEach(cb => cb(...args)); } }",
    "const pipe = (...fns) => (x) => fns.reduce((acc, fn) => fn(acc), x); const transform = pipe(trim, lowercase, capitalize);",
    "const memoize = (fn) => { const cache = new Map(); return (...args) => { const key = JSON.stringify(args); if (!cache.has(key)) cache.set(key, fn(...args)); return cache.get(key); }; };",
    "const flatten = (arr) => arr.reduce((acc, val) => Array.isArray(val) ? acc.concat(flatten(val)) : acc.concat(val), []);",
    "async function retry(fn, retries = 3, delay = 1000) { for (let i = 0; i < retries; i++) { try { return await fn(); } catch (e) { if (i === retries - 1) throw e; await new Promise(r => setTimeout(r, delay)); } } }",
    'const deepClone = (obj) => { if (obj === null || typeof obj !== "object") return obj; const clone = Array.isArray(obj) ? [] : {}; for (const key in obj) { clone[key] = deepClone(obj[key]); } return clone; };',
    "const throttle = (fn, limit) => { let inThrottle; return (...args) => { if (!inThrottle) { fn(...args); inThrottle = true; setTimeout(() => inThrottle = false, limit); } }; };",
    "const groupBy = (arr, key) => arr.reduce((acc, item) => { const group = item[key]; acc[group] = acc[group] || []; acc[group].push(item); return acc; }, {});",
    "class Observable { constructor() { this.observers = []; } subscribe(fn) { this.observers.push(fn); return () => { this.observers = this.observers.filter(obs => obs !== fn); }; } notify(data) { this.observers.forEach(fn => fn(data)); } }",
    "const createStore = (reducer, initialState) => { let state = initialState; const listeners = []; return { getState: () => state, dispatch: (action) => { state = reducer(state, action); listeners.forEach(l => l(state)); }, subscribe: (fn) => { listeners.push(fn); return () => listeners.splice(listeners.indexOf(fn), 1); } }; };",
  ],
  python: [
    "def fibonacci(n): a, b = 0, 1; result = []; [result.append(b) for _ in range(n) if not (a, b := b, a + b) or True]; return result",
    "class DataProcessor: def __init__(self, data): self.data = data def transform(self): return [item.strip().lower() for item in self.data if item]",
    '@app.route("/api/users", methods=["GET"]) def get_users(): users = User.query.all(); return jsonify([u.to_dict() for u in users])',
    "async def fetch_all(urls): async with aiohttp.ClientSession() as session: tasks = [session.get(url) for url in urls]; return await asyncio.gather(*tasks)",
    "from dataclasses import dataclass; @dataclass class Point: x: float; y: float; def distance(self, other): return ((self.x - other.x)**2 + (self.y - other.y)**2)**0.5",
    'def decorator(func): @functools.wraps(func) def wrapper(*args, **kwargs): start = time.time(); result = func(*args, **kwargs); print(f"Took {time.time()-start:.2f}s"); return result; return wrapper',
    'with open("data.json", "r") as f: data = json.load(f); filtered = {k: v for k, v in data.items() if v > threshold}',
    "def merge_sort(arr): if len(arr) <= 1: return arr; mid = len(arr) // 2; left = merge_sort(arr[:mid]); right = merge_sort(arr[mid:]); return merge(left, right)",
    "class Singleton: _instance = None; def __new__(cls): if cls._instance is None: cls._instance = super().__new__(cls); return cls._instance",
    'import pandas as pd; df = pd.read_csv("data.csv"); result = df.groupby("category").agg({"value": ["mean", "sum", "count"]}).reset_index()',
    "def binary_search(arr, target): lo, hi = 0, len(arr) - 1; while lo <= hi: mid = (lo + hi) // 2; if arr[mid] == target: return mid; elif arr[mid] < target: lo = mid + 1; else: hi = mid - 1; return -1",
    "class LinkedList: def __init__(self): self.head = None; def append(self, val): node = Node(val); if not self.head: self.head = node; return; curr = self.head; while curr.next: curr = curr.next; curr.next = node",
    "def flatten(lst): return [item for sublist in lst for item in (flatten(sublist) if isinstance(sublist, list) else [sublist])]",
    'from typing import TypeVar, Generic; T = TypeVar("T"); class Stack(Generic[T]): def __init__(self): self._items: list[T] = []; def push(self, item: T): self._items.append(item); def pop(self) -> T: return self._items.pop()',
    "async def websocket_handler(websocket, path): async for message in websocket: data = json.loads(message); response = await process(data); await websocket.send(json.dumps(response))",
  ],
  typescript: [
    'interface User { id: string; name: string; email: string; role: "admin" | "user"; } type UserUpdate = Partial<Omit<User, "id">>;',
    "function createStore<T>(initial: T): Store<T> { let state = initial; const listeners = new Set<(val: T) => void>(); return { get: () => state, set: (v) => { state = v; listeners.forEach(l => l(v)); }, subscribe: (cb) => { listeners.add(cb); return () => { listeners.delete(cb); }; } }; }",
    "type DeepPartial<T> = { [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P]; };",
    "const useDebounce = <T>(value: T, delay: number): T => { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(timer); }, [value, delay]); return debounced; };",
    'async function fetchWithRetry<T>(url: string, retries: number = 3): Promise<T> { for (let i = 0; i < retries; i++) { try { const res = await fetch(url); return res.json(); } catch (e) { if (i === retries - 1) throw e; await new Promise(r => setTimeout(r, 1000 * 2 ** i)); } } throw new Error("Unreachable"); }',
    "class Queue<T> { private items: T[] = []; enqueue(item: T): void { this.items.push(item); } dequeue(): T | undefined { return this.items.shift(); } peek(): T | undefined { return this.items[0]; } get size(): number { return this.items.length; } }",
    "const validator = z.object({ name: z.string().min(1).max(100), email: z.string().email(), age: z.number().int().positive().optional(), tags: z.array(z.string()).default([]) });",
    "type EventMap = { click: MouseEvent; keydown: KeyboardEvent; resize: Event; }; function on<K extends keyof EventMap>(type: K, handler: (e: EventMap[K]) => void): void { window.addEventListener(type, handler as EventListener); }",
    "const match = <T extends string>(value: T) => ({ when: <R>(pattern: T, fn: () => R) => value === pattern ? { done: () => fn() } : match(value), done: () => undefined });",
    "type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E }; function tryCatch<T>(fn: () => T): Result<T> { try { return { ok: true, value: fn() }; } catch (e) { return { ok: false, error: e as Error }; } }",
    "const router: Router = { routes: new Map(), add(path: string, handler: Handler) { this.routes.set(path, handler); }, resolve(url: string) { const handler = this.routes.get(url); return handler ? handler() : notFound(); } };",
    "type Prettify<T> = { [K in keyof T]: T[K] } & {}; type Merge<A, B> = Prettify<Omit<A, keyof B> & B>;",
    "function pipe<A, B>(fn1: (a: A) => B): (a: A) => B; function pipe<A, B, C>(fn1: (a: A) => B, fn2: (b: B) => C): (a: A) => C; function pipe(...fns: Function[]) { return (x: unknown) => fns.reduce((v, f) => f(v), x); }",
  ],
  rust: [
    "fn fibonacci(n: u32) -> Vec<u64> { let mut fib = vec![0, 1]; for i in 2..n as usize { fib.push(fib[i-1] + fib[i-2]); } fib }",
    "use std::collections::HashMap; fn word_count(text: &str) -> HashMap<&str, usize> { text.split_whitespace().fold(HashMap::new(), |mut acc, word| { *acc.entry(word).or_insert(0) += 1; acc }) }",
    "#[derive(Debug, Clone, Serialize, Deserialize)] struct Config { host: String, port: u16, database_url: String, max_connections: u32 }",
    'async fn handle_request(req: Request<Body>) -> Result<Response<Body>, hyper::Error> { match (req.method(), req.uri().path()) { (&Method::GET, "/health") => Ok(Response::new(Body::from("OK"))), _ => Ok(Response::builder().status(404).body(Body::empty()).unwrap()) } }',
    "impl Iterator for Fibonacci { type Item = u64; fn next(&mut self) -> Option<Self::Item> { let new = self.a + self.b; self.a = self.b; self.b = new; Some(self.a) } }",
    'enum Command { Quit, Echo(String), Print { message: String, newline: bool } } fn execute(cmd: Command) { match cmd { Command::Quit => std::process::exit(0), Command::Echo(s) => print!("{}", s), Command::Print { message, newline } => { print!("{}", message); if newline { println!(); } } } }',
    'trait Drawable { fn draw(&self); fn bounds(&self) -> Rect; } impl Drawable for Circle { fn draw(&self) { println!("Drawing circle at ({}, {}) r={}", self.x, self.y, self.radius); } fn bounds(&self) -> Rect { Rect::new(self.x - self.radius, self.y - self.radius, self.radius * 2.0, self.radius * 2.0) } }',
    "fn parallel_map<T: Send, U: Send>(data: Vec<T>, f: fn(T) -> U) -> Vec<U> { data.into_par_iter().map(f).collect() }",
    'use tokio::sync::mpsc; async fn producer(tx: mpsc::Sender<i32>) { for i in 0..100 { tx.send(i).await.unwrap(); } } async fn consumer(mut rx: mpsc::Receiver<i32>) { while let Some(val) = rx.recv().await { println!("Got: {}", val); } }',
    "impl<T: PartialOrd> BinaryTree<T> { fn insert(&mut self, value: T) { match self { Self::Empty => *self = Self::Node { value, left: Box::new(Self::Empty), right: Box::new(Self::Empty) }, Self::Node { value: ref v, left, right } => { if value < *v { left.insert(value) } else { right.insert(value) } } } } }",
  ],
  go: [
    "func fibonacci(n int) []int { fib := make([]int, n); fib[0], fib[1] = 0, 1; for i := 2; i < n; i++ { fib[i] = fib[i-1] + fib[i-2] }; return fib }",
    'func handleRequest(w http.ResponseWriter, r *http.Request) { switch r.Method { case "GET": users, err := db.GetUsers(); if err != nil { http.Error(w, err.Error(), 500); return }; json.NewEncoder(w).Encode(users) } }',
    "type Stack[T any] struct { items []T } func (s *Stack[T]) Push(item T) { s.items = append(s.items, item) } func (s *Stack[T]) Pop() (T, bool) { if len(s.items) == 0 { var zero T; return zero, false }; item := s.items[len(s.items)-1]; s.items = s.items[:len(s.items)-1]; return item, true }",
    "func worker(jobs <-chan int, results chan<- int) { for j := range jobs { result := process(j); results <- result } }",
    'func middleware(next http.Handler) http.Handler { return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { start := time.Now(); next.ServeHTTP(w, r); log.Printf("%s %s %v", r.Method, r.URL.Path, time.Since(start)) }) }',
    "func Map[T any, U any](slice []T, fn func(T) U) []U { result := make([]U, len(slice)); for i, v := range slice { result[i] = fn(v) }; return result }",
    "type Result[T any] struct { Value T; Err error } func Try[T any](fn func() (T, error)) Result[T] { val, err := fn(); return Result[T]{Value: val, Err: err} }",
    "func (s *Server) Start(ctx context.Context) error { srv := &http.Server{Addr: s.addr, Handler: s.router}; go func() { <-ctx.Done(); srv.Shutdown(context.Background()) }(); return srv.ListenAndServe() }",
    "func BinarySearch[T constraints.Ordered](arr []T, target T) int { lo, hi := 0, len(arr)-1; for lo <= hi { mid := (lo + hi) / 2; if arr[mid] == target { return mid } else if arr[mid] < target { lo = mid + 1 } else { hi = mid - 1 } }; return -1 }",
    "type Cache[K comparable, V any] struct { mu sync.RWMutex; items map[K]V } func (c *Cache[K, V]) Get(key K) (V, bool) { c.mu.RLock(); defer c.mu.RUnlock(); v, ok := c.items[key]; return v, ok } func (c *Cache[K, V]) Set(key K, value V) { c.mu.Lock(); defer c.mu.Unlock(); c.items[key] = value }",
  ],
};

// ===== HELPERS =====

function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function pickRandom<T>(arr: T[], count: number): T[] {
  const shuffled = shuffleArray(arr);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// ===== MAIN EXPORT =====

export function getWords(settings: RoomSettings): string {
  const {
    mode,
    wordCount = 30,
    language = "javascript",
    difficulty = "medium",
    textType = "words",
  } = settings;

  if (mode === "code") {
    const snippets = codeSnippets[language] || codeSnippets.javascript;
    const shuffled = shuffleArray(snippets);
    let text = "";
    for (let i = 0; i < shuffled.length && text.length < wordCount * 8; i++) {
      text += (text ? " " : "") + shuffled[i];
    }
    return text;
  }

  if (mode === "custom") {
    return settings.customText || "Type your custom text here";
  }

  // Words mode - pick based on textType
  if (textType === "sentences") {
    const picked = pickRandom(sentences, Math.ceil(wordCount / 12));
    return picked.join(" ");
  }

  if (textType === "paragraphs") {
    const picked = pickRandom(paragraphs, Math.ceil(wordCount / 50));
    return picked.join(" ");
  }

  if (textType === "quotes") {
    const picked = pickRandom(quotes, Math.ceil(wordCount / 10));
    return picked.join(" ");
  }

  // Default: random words
  let wordList: string[];
  switch (difficulty) {
    case "easy":
      wordList = commonWords;
      break;
    case "hard":
      wordList = hardWords;
      break;
    case "medium":
    default:
      wordList = [...commonWords, ...mediumWords];
  }

  const shuffled = shuffleArray(wordList);
  return shuffled.slice(0, wordCount).join(" ");
}
